### ISSUE TITLE
Check html on travis build

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pupil-docs-website#50]
Use https://github.com/wjdp/htmltest to check for valid:
- links
- internal hashes
- links to scripts
- https
- valid image paths and valid image alt attr
- valid meta tags

add a the `tmp` dir that is created by the htmltest to .gitignore and cache the tmp/.htmltest file via travis.

**Comment by nathakits** [comment]
Travis-build - https://travis-ci.org/pupil-labs/pupil-docs-website/jobs/239915942#L916-L1026

missing alt tags
broken links
missing srcset attributes (this one is a bit tricky because it may be set dynamically with .js lazyloading)

Note that line numbers refer to the built index.html file. So, it would be wise to build the site locally to debug these issues.

Pay attention only to the master branch here and not to other tags. Hence why I highlighted L916-L1026 in the travis

**Comment by willpatera** [comment]
Done.
