### ISSUE TITLE
Tag script not tagging webp images

### ISSUE THREAD

**Issue by nathakits** [pupil-labs/pupil-docs-website#82]
Currently the tag script is only tagging webp images for master and not for other tags. So there are no .webp images for v0912 where we are using them.

![v0912](https://user-images.githubusercontent.com/17331040/27818321-5772114e-60bf-11e7-8c59-edb5d90a2ef5.png)

**Comment by nathakits** [comment]
@willpatera - The problem i assume is from the tag script but i'm not familiar with it and not sure how to fix it.

**Comment by willpatera** [comment]
@nathakits the problem is not related to `tag.sh`. The issue is that there are no `.webp` images for any of the tags. See: https://github.com/pupil-labs/pupil-docs/tree/v0.9.12/images - `.webp` only exists for the `master` branch on `pupil-docs` at the moment. However, templates are not tied to content (docuapi is not in lock-step with pupil-docs) and therefore the templates are requesting resources - `.webp` images - that do not exist in the other branches.
